import React, { useEffect } from 'react';
import { Button } from '@/components/ui/button';
import { Card, CardContent, CardDescription, CardHeader, CardTitle } from '@/components/ui/card';
import { Badge } from '@/components/ui/badge';
import { CheckCircle, Download, Calendar, Trophy, Users, TrendingUp, FileText, QrCode } from 'lucide-react';
import { track } from '@/lib/analytics/track';

const SportsFounding20: React.FC = () => {
  useEffect(() => {
    track('landing_viewed', {
      segment: 'sports',
      utm_source: new URLSearchParams(window.location.search).get('utm_source'),
      utm_medium: new URLSearchParams(window.location.search).get('utm_medium'),
      utm_campaign: new URLSearchParams(window.location.search).get('utm_campaign'),
      utm_content: new URLSearchParams(window.location.search).get('utm_content'),
    });
  }, []);

  const handleBookPreview = () => {
    track('call_booked', { segment: 'sports' });
    window.open('https://calendly.com/boutique-family-office', '_blank');
  };

  const handleDownload = () => {
    track('pdf_downloaded', { segment: 'sports', type: 'digital' });
    // Will be generated by PDF component
  };

  const handleVideoPlay = () => {
    track('video_played', { segment: 'sports', length: 60 });
  };

  const goldTier = ['NFL', 'NBA', 'FIFA', 'UFC', 'MLB'];
  const silverTier = ['Formula 1', 'NASCAR', 'PGA Tour', 'LPGA', 'NHL'];
  const bronzeTier = ['MLS', 'USOC', 'IOC', 'ONE Championship', 'World Rugby', 'ICC (Cricket)', 'Magic Johnson Enterprises', 'A-Rod Corp', 'WADA', 'International Paralympic Committee'];

  return (
    <div className="min-h-screen bg-background">
      {/* Hero Section */}
      <section className="bg-black text-white py-20">
        <div className="max-w-7xl mx-auto px-6">
          <div className="text-center space-y-6">
            <Badge variant="outline" className="border-gold text-gold mb-4">
              Founding 20 • Sports
            </Badge>
            
            <h1 className="text-5xl md:text-6xl font-bold tracking-tight">
              Partner with <span className="text-gold">BFO</span> to
              <br />
              Elevate Player Care
            </h1>
            
            <p className="text-xl text-white/70 max-w-3xl mx-auto leading-relaxed">
              A unified platform for healthspan + wealthspan, built for athlete programs, 
              NIL education, and long-term financial wellbeing.
            </p>
            
            <div className="flex flex-col sm:flex-row gap-4 justify-center items-center mt-8">
              <Button 
                onClick={handleBookPreview}
                size="lg" 
                className="bg-gold text-black hover:bg-gold/90 px-8 py-4 text-lg"
              >
                <Calendar className="h-5 w-5 mr-2" />
                Book a 15-minute preview
              </Button>
              
              <Button 
                onClick={handleDownload}
                variant="outline" 
                size="lg"
                className="border-gold text-gold hover:bg-gold/10 px-8 py-4 text-lg"
              >
                <Download className="h-5 w-5 mr-2" />
                Download the one-pager
              </Button>
            </div>
          </div>
        </div>
      </section>

      {/* Value Propositions */}
      <section className="py-20 bg-background">
        <div className="max-w-7xl mx-auto px-6">
          <div className="grid md:grid-cols-3 gap-8">
            <Card className="bg-black border-gold/30 text-center">
              <CardHeader>
                <Trophy className="h-12 w-12 text-gold mx-auto mb-4" />
                <CardTitle className="text-gold">NIL & Financial Education</CardTitle>
              </CardHeader>
              <CardContent>
                <p className="text-white/70">
                  Athlete-friendly modules, built with compliance in mind for sustainable financial literacy.
                </p>
              </CardContent>
            </Card>

            <Card className="bg-black border-gold/30 text-center">
              <CardHeader>
                <FileText className="h-12 w-12 text-gold mx-auto mb-4" />
                <CardTitle className="text-gold">Secure Legacy Vault™</CardTitle>
              </CardHeader>
              <CardContent>
                <p className="text-white/70">
                  Documents, permissions, audit trail — enterprise-grade security for sensitive data.
                </p>
              </CardContent>
            </Card>

            <Card className="bg-black border-gold/30 text-center">
              <CardHeader>
                <TrendingUp className="h-12 w-12 text-gold mx-auto mb-4" />
                <CardTitle className="text-gold">SWAG™ Retirement Roadmap</CardTitle>
              </CardHeader>
              <CardContent>
                <p className="text-white/70">
                  Science-based planning for short, mid, and long-term financial horizons.
                </p>
              </CardContent>
            </Card>
          </div>
        </div>
      </section>

      {/* Trust Bar */}
      <section className="py-16 bg-black">
        <div className="max-w-7xl mx-auto px-6">
          <div className="text-center space-y-8">
            <h2 className="text-3xl font-bold text-gold">Enterprise-Grade Security & Compliance</h2>
            <div className="grid md:grid-cols-3 gap-6 text-white/70">
              <div className="flex items-center justify-center gap-2">
                <CheckCircle className="h-5 w-5 text-gold" />
                <span>Multi-tenant RBAC • Audit logging</span>
              </div>
              <div className="flex items-center justify-center gap-2">
                <CheckCircle className="h-5 w-5 text-gold" />
                <span>PII-sanitized analytics</span>
              </div>
              <div className="flex items-center justify-center gap-2">
                <CheckCircle className="h-5 w-5 text-gold" />
                <span>White-label ready for leagues & player programs</span>
              </div>
            </div>
          </div>
        </div>
      </section>

      {/* ROI Section */}
      <section className="py-20 bg-background">
        <div className="max-w-7xl mx-auto px-6">
          <div className="text-center space-y-12">
            <h2 className="text-4xl font-bold text-foreground">Why Sports Leagues Choose BFO</h2>
            
            <div className="grid md:grid-cols-3 gap-8">
              <div className="text-center space-y-4">
                <Users className="h-16 w-16 text-emerald mx-auto" />
                <h3 className="text-xl font-semibold">Player Engagement</h3>
                <p className="text-muted-foreground">
                  Measurable literacy outcomes with athlete-centric design and gamified learning paths.
                </p>
              </div>
              
              <div className="text-center space-y-4">
                <Trophy className="h-16 w-16 text-emerald mx-auto" />
                <h3 className="text-xl font-semibold">Co-created Modules</h3>
                <p className="text-muted-foreground">
                  Custom program spaces designed specifically for your league and player demographics.
                </p>
              </div>
              
              <div className="text-center space-y-4">
                <TrendingUp className="h-16 w-16 text-emerald mx-auto" />
                <h3 className="text-xl font-semibold">National Brand, Local Delivery</h3>
                <p className="text-muted-foreground">
                  Licensed advisors provide personalized support while maintaining brand consistency.
                </p>
              </div>
            </div>
          </div>
        </div>
      </section>

      {/* Founding 20 Tiers */}
      <section className="py-20 bg-black">
        <div className="max-w-7xl mx-auto px-6">
          <div className="text-center space-y-12">
            <h2 className="text-4xl font-bold text-gold">Founding 20 Partnership Tiers</h2>
            <p className="text-xl text-white/70 max-w-3xl mx-auto">
              Priority partnerships with the most influential sports organizations globally
            </p>
            
            <div className="grid md:grid-cols-3 gap-8">
              {/* Gold Tier */}
              <Card className="bg-black border-2 border-gold">
                <CardHeader className="text-center">
                  <div className="w-16 h-16 bg-gold rounded-full flex items-center justify-center mx-auto mb-4">
                    <span className="text-2xl">🥇</span>
                  </div>
                  <CardTitle className="text-gold text-2xl">Gold Tier</CardTitle>
                  <CardDescription className="text-white/70">
                    Premier partnerships with global reach
                  </CardDescription>
                </CardHeader>
                <CardContent className="space-y-3">
                  {goldTier.map((org, index) => (
                    <div key={index} className="flex items-center gap-2 text-white">
                      <CheckCircle className="h-4 w-4 text-gold" />
                      <span>{org}</span>
                    </div>
                  ))}
                </CardContent>
              </Card>

              {/* Silver Tier */}
              <Card className="bg-black border-2 border-white/30">
                <CardHeader className="text-center">
                  <div className="w-16 h-16 bg-white/20 rounded-full flex items-center justify-center mx-auto mb-4">
                    <span className="text-2xl">🥈</span>
                  </div>
                  <CardTitle className="text-white text-2xl">Silver Tier</CardTitle>
                  <CardDescription className="text-white/70">
                    Established leagues and tours
                  </CardDescription>
                </CardHeader>
                <CardContent className="space-y-3">
                  {silverTier.map((org, index) => (
                    <div key={index} className="flex items-center gap-2 text-white/80">
                      <CheckCircle className="h-4 w-4 text-white/60" />
                      <span>{org}</span>
                    </div>
                  ))}
                </CardContent>
              </Card>

              {/* Bronze Tier */}
              <Card className="bg-black border-2 border-yellow-600/50">
                <CardHeader className="text-center">
                  <div className="w-16 h-16 bg-yellow-600/20 rounded-full flex items-center justify-center mx-auto mb-4">
                    <span className="text-2xl">🥉</span>
                  </div>
                  <CardTitle className="text-yellow-600 text-2xl">Bronze Tier</CardTitle>
                  <CardDescription className="text-white/70">
                    Growing organizations and enterprises
                  </CardDescription>
                </CardHeader>
                <CardContent className="space-y-2 max-h-60 overflow-y-auto">
                  {bronzeTier.map((org, index) => (
                    <div key={index} className="flex items-center gap-2 text-white/70 text-sm">
                      <CheckCircle className="h-3 w-3 text-yellow-600/60" />
                      <span>{org}</span>
                    </div>
                  ))}
                </CardContent>
              </Card>
            </div>
          </div>
        </div>
      </section>

      {/* CTA Section */}
      <section className="py-20 bg-background">
        <div className="max-w-4xl mx-auto px-6 text-center space-y-8">
          <h2 className="text-4xl font-bold text-foreground">Be one of the Founding 20</h2>
          <p className="text-xl text-muted-foreground leading-relaxed">
            Get concierge onboarding, priority roadmap input, and a preferred partnership tier. 
            Shape the future of athlete financial wellness.
          </p>
          
          <div className="flex flex-col sm:flex-row gap-4 justify-center items-center">
            <Button 
              onClick={handleBookPreview}
              size="lg" 
              className="bg-gold text-black hover:bg-gold/90 px-8 py-4 text-lg"
            >
              <Calendar className="h-5 w-5 mr-2" />
              Book a 15-minute preview
            </Button>
            
            <Button 
              onClick={handleVideoPlay}
              variant="outline" 
              size="lg"
              className="border-gold text-gold hover:bg-gold/10 px-8 py-4 text-lg"
            >
              <QrCode className="h-5 w-5 mr-2" />
              Watch 60s Preview
            </Button>
          </div>
        </div>
      </section>

      {/* Footer */}
      <footer className="bg-black text-white py-12 border-t border-gold/30">
        <div className="max-w-7xl mx-auto px-6 text-center">
          <div className="space-y-4">
            <h3 className="text-2xl font-bold text-gold">Boutique Family Office™</h3>
            <p className="text-white/70">Healthspan + Wealthspan. One Platform.</p>
            <div className="flex justify-center space-x-6 text-sm text-white/60">
              <span>Multi-tenant RBAC</span>
              <span>•</span>
              <span>Audit logging</span>
              <span>•</span>
              <span>Enterprise security</span>
            </div>
          </div>
        </div>
      </footer>
    </div>
  );
};

export default SportsFounding20;