-- Fix Security Issues: Add missing RLS policies and fix SECURITY DEFINER functions

-- 1. Add explicit search_path to all SECURITY DEFINER functions to prevent search path attacks
ALTER FUNCTION public.sha256_hex(text) SET search_path TO 'public', 'pg_temp';
ALTER FUNCTION public.log_education_content_changes() SET search_path TO 'public', 'pg_temp';
ALTER FUNCTION public.set_updated_at() SET search_path TO 'public', 'pg_temp';
ALTER FUNCTION public.receipt_emit(jsonb, jsonb, text, jsonb, uuid, text) SET search_path TO 'public', 'pg_temp';
ALTER FUNCTION public.update_ip_watch_updated_at() SET search_path TO 'public', 'pg_temp';
ALTER FUNCTION public.receipt_emit_secure(jsonb, jsonb, text, jsonb, uuid, text) SET search_path TO 'public', 'pg_temp';
ALTER FUNCTION public.request_receipt_emission(jsonb, jsonb, text, jsonb, uuid, text) SET search_path TO 'public', 'pg_temp';
ALTER FUNCTION public.secure_create_secret(text, text, text) SET search_path TO 'public', 'pg_temp';
ALTER FUNCTION public.fn_touch_updated_at() SET search_path TO 'public', 'pg_temp';
ALTER FUNCTION public.update_estate_requests_updated_at() SET search_path TO 'public', 'pg_temp';
ALTER FUNCTION public.update_education_resources_updated_at() SET search_path TO 'public', 'pg_temp';
ALTER FUNCTION public.complete_attorney_onboarding(uuid) SET search_path TO 'public', 'pg_temp';
ALTER FUNCTION public.get_onboarding_documents(uuid) SET search_path TO 'public', 'pg_temp';
ALTER FUNCTION public.get_table_rls_status() SET search_path TO 'public', 'pg_temp';
ALTER FUNCTION public.get_table_policies() SET search_path TO 'public', 'pg_temp';
ALTER FUNCTION public.update_training_schedule_on_completion() SET search_path TO 'public', 'pg_temp';
ALTER FUNCTION public.get_current_user_organization_id() SET search_path TO 'public', 'pg_temp';
ALTER FUNCTION public.trigger_follow_up_scheduling() SET search_path TO 'public', 'pg_temp';
ALTER FUNCTION public.update_message_thread_timestamp() SET search_path TO 'public', 'pg_temp';
ALTER FUNCTION public.calculate_agency_average_rating(uuid) SET search_path TO 'public', 'pg_temp';
ALTER FUNCTION public.send_onboarding_reminder(uuid) SET search_path TO 'public', 'pg_temp';
ALTER FUNCTION public.update_prospect_invitations_updated_at() SET search_path TO 'public', 'pg_temp';
ALTER FUNCTION public.get_enhanced_security_metrics() SET search_path TO 'public', 'pg_temp';
ALTER FUNCTION public.update_connector_timestamp() SET search_path TO 'public', 'pg_temp';
ALTER FUNCTION public.get_cpa_staff_permissions(uuid) SET search_path TO 'public', 'pg_temp';
ALTER FUNCTION public.trigger_meeting_summary_processing() SET search_path TO 'public', 'pg_temp';
ALTER FUNCTION public.update_agent_ce_credits() SET search_path TO 'public', 'pg_temp';
ALTER FUNCTION public.emit_ad_rds(uuid, jsonb, jsonb, text, jsonb) SET search_path TO 'public', 'pg_temp';
ALTER FUNCTION public.calculate_audit_hash_sha3(uuid, uuid, text, text, text, text) SET search_path TO 'public', 'pg_temp';
ALTER FUNCTION public.update_nil_updated_at() SET search_path TO 'public', 'pg_temp';
ALTER FUNCTION public.current_tenant_id() SET search_path TO 'public', 'pg_temp';
ALTER FUNCTION public.trigger_recompute_trust_score() SET search_path TO 'public', 'pg_temp';
ALTER FUNCTION public.calculate_provider_rating(uuid) SET search_path TO 'public', 'pg_temp';
ALTER FUNCTION public.cleanup_expired_export_requests() SET search_path TO 'public', 'pg_temp';
ALTER FUNCTION public.update_goals_updated_at() SET search_path TO 'public', 'pg_temp';
ALTER FUNCTION public.post_journal(uuid) SET search_path TO 'public', 'pg_temp';
ALTER FUNCTION public.get_current_user_firm_id() SET search_path TO 'public', 'pg_temp';
ALTER FUNCTION public.calculate_retirement_confidence_score(jsonb) SET search_path TO 'public', 'pg_temp';
ALTER FUNCTION public.create_override_payout(uuid) SET search_path TO 'public', 'pg_temp';
ALTER FUNCTION public.count_clients() SET search_path TO 'public', 'pg_temp';
ALTER FUNCTION public.validate_security_status() SET search_path TO 'public', 'pg_temp';
ALTER FUNCTION public.test_audit_logging() SET search_path TO 'public', 'pg_temp';
ALTER FUNCTION public.get_next_audit_block_number(uuid) SET search_path TO 'public', 'pg_temp';
ALTER FUNCTION public.update_support_ticket_timestamp() SET search_path TO 'public', 'pg_temp';
ALTER FUNCTION public.log_seat_activity(uuid, uuid, uuid, text, professional_persona, jsonb, inet, text) SET search_path TO 'public', 'pg_temp';
ALTER FUNCTION public.update_onboarding_status() SET search_path TO 'public', 'pg_temp';
ALTER FUNCTION public.audit_public_schema_extensions() SET search_path TO 'public', 'pg_temp';
ALTER FUNCTION public.cleanup_expired_otp_codes() SET search_path TO 'public', 'pg_temp';
ALTER FUNCTION public.log_referral_audit(text, text, uuid, text, text, uuid, jsonb) SET search_path TO 'public', 'pg_temp';
ALTER FUNCTION public.log_document_access(uuid, text, text, text) SET search_path TO 'public', 'pg_temp';
ALTER FUNCTION public.rpc_database_health() SET search_path TO 'public', 'pg_temp';
ALTER FUNCTION public.test_fk_constraints_cascade() SET search_path TO 'public', 'pg_temp';
ALTER FUNCTION public.verify_file_backup_integrity(uuid) SET search_path TO 'public', 'pg_temp';
ALTER FUNCTION public.get_referral_conversion_analytics(uuid, integer) SET search_path TO 'public', 'pg_temp';
ALTER FUNCTION public.calculate_loan_scenario(numeric, numeric, integer, text, jsonb) SET search_path TO 'public', 'pg_temp';
ALTER FUNCTION public.can_publish_creative(uuid) SET search_path TO 'public', 'pg_temp';
ALTER FUNCTION public.calculate_audit_hash_sha3(text, text, text, bigint, timestamp with time zone, text) SET search_path TO 'public', 'pg_temp';
ALTER FUNCTION public.count_ltc_tests() SET search_path TO 'public', 'pg_temp';
ALTER FUNCTION public.create_default_onboarding_steps(uuid) SET search_path TO 'public', 'pg_temp';
ALTER FUNCTION public.persona_audit_before_insert() SET search_path TO 'public', 'pg_temp';